import { useEffect, useState } from "react";
import API from "../api";

function AdminPanel() {
  const [users, setUsers] = useState([]); const [services, setServices] = useState([]); const [bookings, setBookings] = useState([]); const [stats, setStats] = useState(null); const [error, setError] = useState("");
  const load = () => Promise.all([API.get("/admin/users"), API.get("/admin/services"), API.get("/admin/bookings"), API.get("/admin/dashboard")]).then(([userData, serviceData, bookingData, statData]) => { setUsers(userData.data.users); setServices(serviceData.data.services); setBookings(bookingData.data.bookings); setStats(statData.data.dashboard); }).catch((err) => setError(err.response?.data?.message || "Could not load administration data."));
  useEffect(() => { load(); }, []);
  const changeRole = async (id, role) => { try { await API.put(`/admin/users/${id}/role`, { role }); load(); } catch (err) { alert(err.response?.data?.message || "Could not update role."); } };
  const deleteService = async (id) => { if (!window.confirm("Delete this service?")) return; try { await API.delete(`/admin/services/${id}`); load(); } catch (err) { alert(err.response?.data?.message || "Could not delete service."); } };
  return <div className="min-h-screen bg-gray-100 p-8"><h1 className="text-4xl font-bold text-red-600 mb-8">Admin Panel</h1>{error && <p className="text-red-600 mb-4">{error}</p>}
    {stats && <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 mb-6">{[["Users", stats.totalUsers], ["Experts", stats.totalExperts], ["Services", stats.totalServices], ["Bookings", stats.totalBookings], ["Revenue", `₹${stats.totalRevenue}`]].map(([label, value]) => <div key={label} className="bg-white rounded-xl shadow p-5"><p className="text-gray-500">{label}</p><p className="text-2xl font-bold">{value}</p></div>)}</div>}
    <section className="bg-white shadow-lg rounded-xl p-6 mb-6"><h2 className="text-2xl font-bold mb-4">Users</h2><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-red-100"><th className="border p-3 text-left">Name</th><th className="border p-3 text-left">Email</th><th className="border p-3 text-left">Role</th></tr></thead><tbody>{users.map((user) => <tr key={user._id}><td className="border p-3">{user.name}</td><td className="border p-3">{user.email}</td><td className="border p-3"><select value={user.role} onChange={(e) => changeRole(user._id, e.target.value)} className="border rounded p-1"><option value="user">User</option><option value="expert">Expert</option><option value="admin">Admin</option></select></td></tr>)}</tbody></table></div></section>
    <section className="bg-white shadow-lg rounded-xl p-6 mb-6"><h2 className="text-2xl font-bold mb-4">Services</h2><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-red-100"><th className="border p-3 text-left">Title</th><th className="border p-3 text-left">Provider</th><th className="border p-3 text-left">Action</th></tr></thead><tbody>{services.map((service) => <tr key={service._id}><td className="border p-3">{service.title}</td><td className="border p-3">{service.provider?.name || "—"}</td><td className="border p-3"><button onClick={() => deleteService(service._id)} className="bg-red-600 text-white px-3 py-1 rounded">Delete</button></td></tr>)}</tbody></table></div></section>
    <section className="bg-white shadow-lg rounded-xl p-6"><h2 className="text-2xl font-bold mb-4">Bookings</h2><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-red-100"><th className="border p-3 text-left">Customer</th><th className="border p-3 text-left">Service</th><th className="border p-3 text-left">Date</th><th className="border p-3 text-left">Status</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking._id}><td className="border p-3">{booking.customer?.name}</td><td className="border p-3">{booking.service?.title}</td><td className="border p-3">{new Date(booking.bookingDate).toLocaleDateString()}</td><td className="border p-3 capitalize">{booking.status}</td></tr>)}</tbody></table></div></section>
  </div>;
}
export default AdminPanel;
