import { useEffect, useState } from "react";
import API from "../api";

function ExpertDashboard() {
  const [user, setUser] = useState(null); const [bookings, setBookings] = useState([]); const [error, setError] = useState(""); const [serviceForm, setServiceForm] = useState({ title: "", description: "", category: "", price: "", location: "" }); const [creating, setCreating] = useState(false);
  const load = () => Promise.all([API.get("/auth/me"), API.get("/bookings/expert")]).then(([profile, bookingData]) => { setUser(profile.data.user); setBookings(bookingData.data.bookings); }).catch((err) => setError(err.response?.data?.message || "Could not load dashboard."));
  useEffect(() => { load(); }, []);
  const update = async (id, action) => { try { await API.put(`/bookings/${action}/${id}`); load(); } catch (err) { alert(err.response?.data?.message || "Could not update booking."); } };
  const createService = async (event) => { event.preventDefault(); setCreating(true); try { const { data } = await API.post("/services/create", serviceForm); alert(data.message); setServiceForm({ title: "", description: "", category: "", price: "", location: "" }); } catch (err) { alert(err.response?.data?.message || "Could not create service."); } finally { setCreating(false); } };
  return <div className="min-h-screen bg-gray-100 p-8"><h1 className="text-4xl font-bold text-purple-600 mb-8">Expert Dashboard</h1>{error && <p className="text-red-600 mb-4">{error}</p>}
    <div className="bg-white shadow-lg rounded-xl p-6 mb-6"><h2 className="text-2xl font-bold mb-4">Expert Profile</h2>{user && <div className="space-y-2"><p><strong>Name:</strong> {user.name}</p><p><strong>Service:</strong> {user.category || "Not set"}</p><p><strong>Experience:</strong> {user.experience || 0} years</p><p><strong>Phone:</strong> {user.phone || "Not provided"}</p></div>}</div>
    <div className="bg-white shadow-lg rounded-xl p-6 mb-6"><h2 className="text-2xl font-bold mb-4">Publish a Service</h2><form onSubmit={createService} className="grid md:grid-cols-2 gap-4"><input required placeholder="Service title" value={serviceForm.title} onChange={(e) => setServiceForm({ ...serviceForm, title: e.target.value })} className="border p-3 rounded" /><input required placeholder="Category" value={serviceForm.category} onChange={(e) => setServiceForm({ ...serviceForm, category: e.target.value })} className="border p-3 rounded" /><input required type="number" min="0" placeholder="Price" value={serviceForm.price} onChange={(e) => setServiceForm({ ...serviceForm, price: e.target.value })} className="border p-3 rounded" /><input required placeholder="Location" value={serviceForm.location} onChange={(e) => setServiceForm({ ...serviceForm, location: e.target.value })} className="border p-3 rounded" /><textarea required placeholder="Description" value={serviceForm.description} onChange={(e) => setServiceForm({ ...serviceForm, description: e.target.value })} className="border p-3 rounded md:col-span-2" /><button disabled={creating} className="bg-purple-600 text-white px-4 py-3 rounded md:col-span-2">{creating ? "Publishing..." : "Publish Service"}</button></form></div>
    <div className="bg-white shadow-lg rounded-xl p-6"><h2 className="text-2xl font-bold mb-4">Service Requests</h2><div className="overflow-x-auto"><table className="w-full"><thead><tr className="bg-purple-100"><th className="border p-3 text-left">Customer</th><th className="border p-3 text-left">Service</th><th className="border p-3 text-left">Status</th><th className="border p-3 text-left">Action</th></tr></thead><tbody>{bookings.map((booking) => <tr key={booking._id}><td className="border p-3">{booking.customer?.name}</td><td className="border p-3">{booking.service?.title}</td><td className="border p-3 capitalize">{booking.status}</td><td className="border p-3">{booking.status === "pending" && <><button onClick={() => update(booking._id, "accept")} className="bg-green-500 text-white px-3 py-1 rounded mr-2">Accept</button><button onClick={() => update(booking._id, "reject")} className="bg-red-500 text-white px-3 py-1 rounded">Reject</button></>}{booking.status === "accepted" && <button onClick={() => update(booking._id, "complete")} className="bg-blue-500 text-white px-3 py-1 rounded">Complete</button>}</td></tr>)}</tbody></table>{!bookings.length && <p className="text-center text-gray-500 pt-4">No service requests yet.</p>}</div></div>
  </div>;
}
export default ExpertDashboard;
